### ISSUE TITLE
Problem in Chainbridge

### ISSUE THREAD

**Issue by asilenced** [asilenced/chainbridge#1]
My project is using Next.
There is a Solana Trading View Homepage.
I want to add tradingView widget on my project.
If you have experience of that especially for this field, help me.

**Comment by 486xtm** [comment]
> My project is using Next. There is a Solana Trading View Homepage. I want to add tradingView widget on my project. If you have experience of that especially for this field, help me.

Hi @asilenced .
follow these steps and you will get success.

import { useEffect, useRef } from 'react';

const SolanaTradingViewWidget = () => {
const containerRef = useRef();

useEffect(() => {
const script = document.createElement('script');
script.src = 'https://s3.tradingview.com/tv.js';
script.async = true;
script.onload = () => {
new window.TradingView.widget({
container_id: containerRef.current.id,
width: '100%',
height: 500,
symbol: 'BINANCE:SOLUSDT', // Symbol for Solana on Binance
interval: 'D',
timezone: 'Etc/UTC',
theme: 'dark',
style: '1',
locale: 'en',
toolbar_bg: '#f1f3f6',
enable_publishing: false,
withdateranges: true,
hide_side_toolbar: false,
allow_symbol_change: true,
show_popup_button: true,
popup_width: '1000',
popup_height: '650',
});
};
document.body.appendChild(script);
}, []);

return

;
};
export default SolanaTradingViewWidget;

**Comment by asilenced** [comment]
> > My project is using Next. There is a Solana Trading View Homepage. I want to add tradingView widget on my project. If you have experience of that especially for this field, help me.
> 
> Hi @asilenced . follow these steps and you will get success.
> 
> import { useEffect, useRef } from 'react';
> 
> const SolanaTradingViewWidget = () => { const containerRef = useRef();
> 
> useEffect(() => { const script = document.createElement('script'); script.src = 'https://s3.tradingview.com/tv.js'; script.async = true; script.onload = () => { new window.TradingView.widget({ container_id: containerRef.current.id, width: '100%', height: 500, symbol: 'BINANCE:SOLUSDT', // Symbol for Solana on Binance interval: 'D', timezone: 'Etc/UTC', theme: 'dark', style: '1', locale: 'en', toolbar_bg: '#f1f3f6', enable_publishing: false, withdateranges: true, hide_side_toolbar: false, allow_symbol_change: true, show_popup_button: true, popup_width: '1000', popup_height: '650', }); }; document.body.appendChild(script); }, []);
> 
> return
> 
> ; }; export default SolanaTradingViewWidget;

Thanks.
But how can I use this componet?

**Comment by 486xtm** [comment]
> But how can I use this componet?

You can import this component and use Landing page.

**Comment by asilenced** [comment]
> > But how can I use this componet?
> 
> You can import this component and use Landing page.

Thanks @486xtm, your suggestion resolved the issue! I'll go ahead and close this now.

**Comment by asilenced** [comment]
After implementing this style, it still doesn't work well. Please provide more details.

**Comment by 486xtm** [comment]
> After implementing this style, it still doesn't work well. Please provide more details.

Oh , Sorry .. I missed some css style.. you have to add 'width: 100%'..

**Comment by asilenced** [comment]
> > After implementing this style, it still doesn't work well. Please provide more details.
> 
> Oh , Sorry .. I missed some css style.. you have to add 'width: 100%'..

Thanks again @486xtm, I retried with your suggestion and solved the issue completely.
